// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pref.proto

package proto

import go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Prefecture) Validate() error {
	return nil
}
func (this *GetPrefecturesResponse) Validate() error {
	for _, item := range this.Prefectures {
		if item != nil {
			if err := go_proto_validators.CallValidatorIfExists(item); err != nil {
				return go_proto_validators.FieldError("Prefectures", err)
			}
		}
	}
	return nil
}
